Make it compile
Without this it would not compile with rustc 1.63.0:

    error[E0597]: `settings` does not live long enough
       --> src/read.rs:385:53
        |
    385 |         TokenReader(parse(charswithpos.into_iter(), &settings)).read(depth_fuel)
        |         --------------------------------------------^^^^^^^^^--
        |         |                                           |
        |         |                                           borrowed value does not live long enough
        |         a temporary with access to the borrow is created here ...
    386 |     }
        |     -
        |     |
        |     `settings` dropped here while still borrowed
        |     ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `TokenReader<impl Iterator<Item = Result<TokenWithPos, ParseErrorWithPos>>>`
        |
        = note: the temporary is part of an expression at the end of a block;
                consider forcing this temporary to be dropped sooner, before the block's local variables are dropped
    help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
        |
    385 |         let x = TokenReader(parse(charswithpos.into_iter(), &settings)).read(depth_fuel); x
        |         +++++++                                                                         +++